/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Database.DBMS;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Madushanka
 */
public class loadingAndUnloding extends javax.swing.JFrame {

    /**
     * Creates new form grn
     */
    public loadingAndUnloding() {
        initComponents();
        loadCate();
        loadVehi();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    String l_id = "0";
    String qty = "0";
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(200, 200, 242));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Loading & Unloading", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 20), new java.awt.Color(0, 0, 204))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(200, 200, 242));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Add product details", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 15), new java.awt.Color(0, 51, 153)))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setText("Category");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setToolTipText("");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setText("<html>Name &<br/>Weight</html>");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setText("Selling price");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel12.setText("Unit in Box");

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox2.setToolTipText("");

        jComboBox4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox4.setToolTipText("");

        jComboBox6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox6.setToolTipText("");
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setText("Product ID");

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField9KeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(36, 36, 36)
                                .addComponent(jTextField9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(18, 18, Short.MAX_VALUE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(47, 47, 47)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(53, 53, 53)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 6, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(43, 43, 43)
                        .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Loading ID", "Product ID", "Category", "Name", "Weight", "Sell Price", "Box In Qty", "BOX", "Unbox Qty", "Qty", "<html>Loading<br/>Box</html>", "<html>Loading<br/>UnBox Qty</html>"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
            jTable1.getColumnModel().getColumn(8).setResizable(false);
            jTable1.getColumnModel().getColumn(9).setResizable(false);
        }

        jButton2.setBackground(new java.awt.Color(255, 102, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Loading History");
        jButton2.setContentAreaFilled(false);
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 204, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Add Product");
        jButton3.setContentAreaFilled(false);
        jButton3.setOpaque(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/refresh.png"))); // NOI18N
        jButton9.setContentAreaFilled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 204, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("UNLoading");
        jButton5.setContentAreaFilled(false);
        jButton5.setOpaque(true);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setText("Amount         :");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("0.00");

        jButton4.setBackground(new java.awt.Color(102, 0, 102));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Print Loading");
        jButton4.setContentAreaFilled(false);
        jButton4.setOpaque(true);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(102, 102, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("Exchange");
        jButton6.setContentAreaFilled(false);
        jButton6.setOpaque(true);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel10.setText("Vehicle");

        jComboBox7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox7.setToolTipText("");
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 153, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("Loading");
        jButton7.setContentAreaFilled(false);
        jButton7.setOpaque(true);
        jButton7.setPreferredSize(new java.awt.Dimension(131, 31));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setText("Date");

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jDateChooser1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)))
                                .addGap(24, 24, 24))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(23, 23, 23)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jButton4)
                    .addComponent(jLabel30))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code her
        loadTable();
        loadCate();
        loadVehi();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
                   try {
       if(jComboBox1.getItemCount()!=0){
       String c_n = jComboBox1.getSelectedItem().toString();
       jComboBox6.removeAllItems();
                if(c_n.equals("All")){
                ResultSet rs1 = DBMS.search("SELECT * FROM stock");
                    while (rs1.next()) {                        
                        String name = rs1.getString("name");
                        String weight = rs1.getString("weight");
                        String sp = " ";
                        String n_s_w = name+sp+weight;
                        jComboBox6.addItem(n_s_w);
                    }
                }else{
                    jLabel9.setText(" ");
                ResultSet rs = DBMS.search("SELECT * FROM category WHERE `name`='"+c_n+"'");
                if(rs.next()){
                 String c_id = rs.getString("id");
                 ResultSet rs1 = DBMS.search("SELECT * FROM stock WHERE `cate_id`='"+c_id+"'");
                    while (rs1.next()) {                        
                        String name = rs1.getString("name");
                        String weight = rs1.getString("weight");
                        String sp = " ";
                        String n_s_w = name+sp+weight;
                        jComboBox6.addItem(n_s_w);
                    }
                }
                }
           }
           } catch (Exception e) {
               System.out.println(e);
           }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        // TODO add your handling code here:
        loadTable();
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void jTextField9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyReleased
        // TODO add your handling code here:
       /* try {
            String id = jTextField9.getText();
            ResultSet rs = DBMS.search("SELECT * FROM stock WHERE `id`='"+id+"'");
            if(rs.next()==true){
                String cate = rs.getString("cate_id");
                ResultSet rs1 = DBMS.search("SELECT * FROM category WHERE `id`='"+cate+"'");
                if(rs1.next()){
                String cate_n = rs1.getString("name");
                jComboBox1.setSelectedItem(cate_n);
                }
                String name = rs.getString("name");
                jComboBox6.addItem(name);
                jComboBox6.setSelectedItem(name);
                String bp = rs.getString("buy_p");
                String sp = rs.getString("sell_p");
                jComboBox4.addItem(sp);
                jComboBox4.setSelectedItem(sp);
                String wei = rs.getString("weight");
                jComboBox3.addItem(wei);
                jComboBox3.setSelectedItem(wei);
                String ub = rs.getString("qty_i_b");
                jComboBox2.addItem(ub);
                jComboBox2.setSelectedItem(ub);
                jLabel18.setText(ub);
                String qty = rs.getString("qty");
                jLabel19.setText(qty);
            }else{
                jComboBox2.removeAllItems();
                jComboBox3.removeAllItems();
                jComboBox4.removeAllItems();
                jComboBox6.removeAllItems();
                jLabel18.setText("0");
                jLabel19.setText("0");
                jTextField7.setText("0");
                jTextField6.setText("0");
                jTextField8.setText("0");
                loadCate();
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }*/
    }//GEN-LAST:event_jTextField9KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        load_history l = new load_history();
        l.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //loading
        TableModel tm = jTable1.getModel();
        DefaultTableModel dtm = (DefaultTableModel)tm;
        try {
              String p_id = jTextField9.getText();
       String v = jComboBox7.getSelectedItem().toString();
       String q = "0";
       if(!p_id.isEmpty()){
           ResultSet rs = DBMS.search("SELECT * FROM loading WHERE `vehicle_num`='"+v+"' AND `stock_id`='"+p_id+"' ");
          if(rs.next()==false){
           DBMS.iud("INSERT INTO loading(`stock_id`,`vehicle_num`,`qty` ) VALUE('"+p_id+"','"+v+"','"+q+"')");
            ResultSet rs1 = DBMS.search("SELECT * FROM loading WHERE `vehicle_num`='"+v+"' AND `stock_id`='"+p_id+"' ");
            if(rs1.next()){
            Vector<String> v1 = new Vector<>();
            v1.add(rs1.getString("id"));
            v1.add(rs1.getString("stock_id"));
             ResultSet rs2 = DBMS.search("SELECT * FROM stock WHERE `id`='"+rs1.getString("stock_id")+"'");
             if(rs2.next()){
             ResultSet rs3 = DBMS.search("SELECT `name` FROM category WHERE `id`='"+rs2.getString("cate_id")+"'");
              if(rs3.next()){
                  v1.add(rs3.getString("name"));
              }
              v1.add(rs2.getString("name"));
              v1.add(rs2.getString("weight"));
              v1.add(rs2.getString("sell_p"));
              v1.add(rs2.getString("qty_i_b"));
              v1.add("0");
              v1.add("0");
              v1.add("0");
              v1.add("0");
              v1.add("0");
              
             }
             dtm.addRow(v1);
            }
            JOptionPane.showMessageDialog(this, "Success", "Add Loading Product", JOptionPane.INFORMATION_MESSAGE);
          }else{
          JOptionPane.showMessageDialog(this, "This Product Allready Add", "Add Loading Product", JOptionPane.INFORMATION_MESSAGE);
          }
          
       }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         /* if(evt.getClickCount()==2){
            int row = jTable1.getSelectedRow();
            l_id = jTable1.getValueAt(row, 0).toString();
            jTextField9.setText(jTable1.getValueAt(row, 1).toString());
            String cate = jTable1.getValueAt(row, 2).toString();
            jComboBox1.setSelectedItem(cate);
            String name = jTable1.getValueAt(row, 3).toString();
            jComboBox6.addItem(name);
            jComboBox6.setSelectedItem(name);
            String weight = jTable1.getValueAt(row, 4).toString();
            jComboBox3.addItem(weight);
            jComboBox3.setSelectedItem(weight);
            String s_p = jTable1.getValueAt(row, 5).toString();
            jComboBox4.addItem(s_p);
            jComboBox4.setSelectedItem(s_p);
            String b_qty = jTable1.getValueAt(row, 6).toString();
            jComboBox2.addItem(b_qty);
            jComboBox2.setSelectedItem(b_qty);
            jLabel18.setText(b_qty);
            jTextField7.setText(jTable1.getValueAt(row, 7).toString());
            jTextField6.setText(jTable1.getValueAt(row, 8).toString());
            jTextField8.setText(jTable1.getValueAt(row, 9).toString());
            qty = jTable1.getValueAt(row, 9).toString();
        }*/
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
/*        // TODO add your handling code here:
        try {
            int row = jTable1.getSelectedRow();
            if(row!=-1){
            String p_id = jTable1.getValueAt(row, 1).toString();
            String l_id = jTable1.getValueAt(row, 0).toString();
            String q = jTable1.getValueAt(row, 9).toString();
            ResultSet rs = DBMS.search("SELECT * FROM stock WHERE `id`='"+p_id+"' ");
            if(rs.next()){
                String n_q = rs.getString("qty");
                Double d_t_q = Double.valueOf(q);
                Double d_n_q = Double.valueOf(n_q);
                Double aa = d_t_q+d_n_q;
                int a = aa.intValue();
                DBMS.iud("UPDATE stock SET `qty`='"+String.valueOf(a)+"' WHERE `id`='"+p_id+"'");
                DBMS.iud("DELETE FROM loading WHERE `id`='"+l_id+"'");
                loadTable();
                JOptionPane.showMessageDialog(this, "Success", "Unloading Product", JOptionPane.INFORMATION_MESSAGE);
            }
            }else{
             JOptionPane.showMessageDialog(this, "Please select product", "Unloading Product", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            System.out.println(e);
        }*/
        try {
            if(jDateChooser1.getDate()!=null){
            int rc = jTable1.getRowCount();
             SimpleDateFormat sdf =new SimpleDateFormat("yyyy-MM-dd");
             String date = sdf.format(jDateChooser1.getDate());
             for(int x = 0;x<rc;x++){
             String v = jComboBox7.getSelectedItem().toString();
                String b = "Balance stock";
                String u = "Unloading";
                ResultSet rs8 = DBMS.search("SELECT * FROM st_info WHERE `type`='"+b+"' AND `vehicle_f`='"+v+"' AND `date`='"+date+"' ");
            if(rs8.next()==false){
            DBMS.iud("INSERT INTO st_info(`vehicle_f`,`vehicle_t`,`type`,`date`) VALUES ('"+v+"','"+v+"','"+b+"','"+date+"')");
            ResultSet rs9 = DBMS.search("SELECT * FROM st_info WHERE `type`='"+b+"' AND `vehicle_f`='"+v+"' AND `date`='"+date+"' ");
            String b_s_id = "0";
            if(rs9.next()){
                b_s_id = rs9.getString("id");
            }
            ResultSet rs10 = DBMS.search("SELECT * FROM loading WHERE `vehicle_num`='"+v+"' ");
            while(rs10.next()){
            String st_id = rs10.getString("stock_id");
            String q = rs10.getString("qty");
            DBMS.iud("INSERT INTO st_details(`st_info_id`,`stock_id`,`qty`) VALUES ('"+b_s_id+"','"+st_id+"','"+q+"')");
            }
            }
            String b_q = jTable1.getValueAt(x, 10).toString();
            String ub_q = jTable1.getValueAt(x, 11).toString();
            if(!b_q.equals("0")|!ub_q.equals("0")){
            String p_id = jTable1.getValueAt(x, 1).toString();
            ResultSet rs = DBMS.search("SELECT * FROM loading WHERE `vehicle_num`='"+v+"' AND `stock_id`='"+p_id+"' ");
            if(rs.next()){
            String n_qty = rs.getString("qty");
            String biq = jTable1.getValueAt(x, 6).toString();
            Double d_t_bq = Double.valueOf(b_q);
            Double d_t_ubq = Double.valueOf(ub_q);
            Double d_n_qt = Double.valueOf(n_qty);
            Double d_biq = Double.valueOf(biq);
            Double d_all_q = 0.00;
            Double d_all_q1 = d_t_bq*d_biq+d_t_ubq;
            d_all_q = d_n_qt-d_all_q1; 
            int y = d_all_q.intValue();
            String l_id = jTable1.getValueAt(x, 0).toString();
            DBMS.iud("UPDATE loading SET `qty`='"+String.valueOf(y)+"' WHERE `stock_id`='"+p_id+"' AND `vehicle_num`='"+v+"'");
            
            ResultSet rs10 = DBMS.search("SELECT * FROM st_info WHERE `type`='"+u+"' AND `vehicle_f`='"+v+"' AND `date`='"+date+"' ");
            if(rs10.next()==false){
            DBMS.iud("INSERT INTO st_info(`vehicle_f`,`vehicle_t`,`type`,`date`) VALUES ('"+v+"','"+v+"','"+u+"','"+date+"')");
            }
            ResultSet rs11 = DBMS.search("SELECT * FROM st_info WHERE `type`='"+u+"' AND `vehicle_f`='"+v+"' AND `date`='"+date+"' ");
            String l_s_id = "";
            if(rs11.next()){
                l_s_id = rs11.getString("id");
            }
            Double qq = d_t_bq*d_biq+d_t_ubq;
            int q = qq.intValue();
            DBMS.iud("INSERT INTO st_details(`st_info_id`,`stock_id`,`qty`) VALUES ('"+l_s_id+"','"+p_id+"','"+String.valueOf(q)+"')");
            
            ResultSet rs1 = DBMS.search("SELECT * FROM stock WHERE `id`='"+p_id+"' ");
            if(rs1.next()){
                String sn_qty = rs1.getString("qty");
                Double d_sn_qt = Double.valueOf(sn_qty);
                Double xx = d_t_bq*d_biq;
                        xx+=d_t_ubq;
                Double aa = d_sn_qt+xx;
                int yy = aa.intValue();
                DBMS.iud("UPDATE stock SET `qty`='"+String.valueOf(yy)+"' WHERE `id`='"+p_id+"'");
                
            }
            }
        }
            
            }
             loadTable();
            }else{
            JOptionPane.showMessageDialog(this, "Please Select Date", "Loading", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String vehi = jComboBox7.getSelectedItem().toString();
        String amu = jLabel24.getText();
        TableModel tm = jTable1.getModel();
        loading_report lr = new loading_report(tm, amu, vehi);
        //lr.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
       if(jComboBox6.getItemCount()!=0){
           String c_n = jComboBox1.getSelectedItem().toString();
           try {
               if(c_n.equals("All")){
               String txt = jComboBox6.getSelectedItem().toString();
               String name = txt.replaceAll("\\d", "");
               name = name.replaceAll(".$", "");
               name = name.trim();
               String n = name;
               String weight = txt.replaceAll("[^\\d.]", "");
               String g = "g";
               String wg = weight+g;
                 ResultSet rs2 = DBMS.search("SELECT * FROM stock WHERE `name`='"+n+"' AND `weight`='"+wg+"'");
                 if(rs2.next()){
                 String id = rs2.getString("id");
                 String sp = rs2.getString("sell_p");
                 String ub = rs2.getString("qty_i_b");
                 String c = rs2.getString("cate_id");
                 ResultSet rs3 = DBMS.search("SELECT * FROM category WHERE `id`='"+c+"'");
                 if(rs3.next()){
                 //jComboBox1.setSelectedItem(rs3.getString("name"));
                 jLabel9.setText(rs3.getString("name"));
                 }
                 jComboBox4.removeAllItems();
                 jComboBox2.removeAllItems();
                 jComboBox4.addItem(sp);
                 jComboBox2.addItem(ub);
                 jTextField9.setText(id);
                
                 }
               }else{
               String txt = jComboBox6.getSelectedItem().toString();      
               String name = txt.replaceAll("\\d", "");
               name = name.replaceAll(".$", "");
               name = name.trim();
               String n = name;
               String weight = txt.replaceAll("[^\\d.]", "");
               String g = "g";
               String wg = weight+g;
                ResultSet rs = DBMS.search("SELECT * FROM category WHERE `name`='"+c_n+"'");
                if(rs.next()){
                 String c_id = rs.getString("id");
                 /*System.out.println(name);
                 System.out.println(wg);
                 System.out.println(c_id);*/
                 ResultSet rs2 = DBMS.search("SELECT * FROM stock WHERE `cate_id`='"+c_id+"' AND `name`='"+n+"' AND `weight`='"+wg+"'");
                 if(rs2.next()){
                 String id = rs2.getString("id");
                 String sp = rs2.getString("sell_p");
                 String ub = rs2.getString("qty_i_b");
                 jComboBox4.removeAllItems();
                 jComboBox2.removeAllItems();
                 jComboBox4.addItem(sp);
                 jComboBox2.addItem(ub);
                 jTextField9.setText(id);
                 }
                }
               }
           } catch (Exception e) {
               System.out.println(e);
           }
       }else{
       jTextField9.setText("");
       jComboBox4.removeAllItems();
       jComboBox2.removeAllItems();
       }
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        load_exchange l = new load_exchange();
        l.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try {
             if(jDateChooser1.getDate()!=null){
             int rc = jTable1.getRowCount();
             SimpleDateFormat sdf =new SimpleDateFormat("yyyy-MM-dd");
             String date = sdf.format(jDateChooser1.getDate());
        for(int x = 0;x<rc;x++){
            String v = jComboBox7.getSelectedItem().toString();
                String b = "Balance stock";
                String l = "Loading";
            ResultSet rs8 = DBMS.search("SELECT * FROM st_info WHERE `type`='"+b+"' AND `vehicle_f`='"+v+"' AND `date`='"+date+"' ");
            if(rs8.next()==false){
            DBMS.iud("INSERT INTO st_info(`vehicle_f`,`vehicle_t`,`type`,`date`) VALUES ('"+v+"','"+v+"','"+b+"','"+date+"')");
            ResultSet rs9 = DBMS.search("SELECT * FROM st_info WHERE `type`='"+b+"' AND `vehicle_f`='"+v+"' AND `date`='"+date+"' ");
            String b_s_id = "0";
            if(rs9.next()){
                b_s_id = rs9.getString("id");
            }
            ResultSet rs10 = DBMS.search("SELECT * FROM loading WHERE `vehicle_num`='"+v+"' ");
            while(rs10.next()){
            String st_id = rs10.getString("stock_id");
            String q = rs10.getString("qty");
            DBMS.iud("INSERT INTO st_details(`st_info_id`,`stock_id`,`qty`) VALUES ('"+b_s_id+"','"+st_id+"','"+q+"')");
            }
            }
            
            String b_q = jTable1.getValueAt(x, 10).toString();
            String ub_q = jTable1.getValueAt(x, 11).toString();
        if(!b_q.equals("0")|!ub_q.equals("0")){
            String p_id = jTable1.getValueAt(x, 1).toString();
            ResultSet rs = DBMS.search("SELECT * FROM loading WHERE `vehicle_num`='"+v+"' AND `stock_id`='"+p_id+"' ");
            if(rs.next()){
            String n_qty = rs.getString("qty");
            String biq = jTable1.getValueAt(x, 6).toString();
            Double d_t_bq = Double.valueOf(b_q);
            Double d_t_ubq = Double.valueOf(ub_q);
            Double d_n_qt = Double.valueOf(n_qty);
            Double d_biq = Double.valueOf(biq);
            Double d_all_q = 0.00;
            d_all_q += d_n_qt+d_t_ubq;
            d_all_q += d_t_bq*d_biq;
            int y = d_all_q.intValue();
            String l_id = jTable1.getValueAt(x, 0).toString();
            DBMS.iud("UPDATE loading SET `qty`='"+String.valueOf(y)+"' WHERE `stock_id`='"+p_id+"' AND `vehicle_num`='"+v+"'");
            
            ResultSet rs10 = DBMS.search("SELECT * FROM st_info WHERE `type`='"+l+"' AND `vehicle_f`='"+v+"' AND `date`='"+date+"' ");
            if(rs10.next()==false){
            DBMS.iud("INSERT INTO st_info(`vehicle_f`,`vehicle_t`,`type`,`date`) VALUES ('"+v+"','"+v+"','"+l+"','"+date+"')");
            }
            ResultSet rs11 = DBMS.search("SELECT * FROM st_info WHERE `type`='"+l+"' AND `vehicle_f`='"+v+"' AND `date`='"+date+"' ");
            String l_s_id = "";
            if(rs11.next()){
                l_s_id = rs11.getString("id");
            }
            Double qq = d_t_bq*d_biq+d_t_ubq;
            int q = qq.intValue();
            DBMS.iud("INSERT INTO st_details(`st_info_id`,`stock_id`,`qty`) VALUES ('"+l_s_id+"','"+p_id+"','"+String.valueOf(q)+"')");
            
            ResultSet rs1 = DBMS.search("SELECT * FROM stock WHERE `id`='"+p_id+"' ");
            if(rs1.next()){
                String sn_qty = rs1.getString("qty");
                Double d_sn_qt = Double.valueOf(sn_qty);
                Double xx = d_t_bq*d_biq;
                        xx+=d_t_ubq;
                Double aa = d_sn_qt-xx;
                int yy = aa.intValue();
                DBMS.iud("UPDATE stock SET `qty`='"+String.valueOf(yy)+"' WHERE `id`='"+p_id+"'");
                
            }
            }
        }
        }
        loadTable();
             }else{
             JOptionPane.showMessageDialog(this, "Please Select Date", "Loading", JOptionPane.INFORMATION_MESSAGE);
             }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loadingAndUnloding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loadingAndUnloding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loadingAndUnloding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loadingAndUnloding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loadingAndUnloding().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
public void loadCate(){
    try{
ResultSet rs = DBMS.search("SELECT * FROM category");
jComboBox1.removeAllItems();
           jComboBox1.addItem("All");
          while (rs.next()) {              
              String name = rs.getString("name");
              jComboBox1.addItem(name);
          }
      } catch (Exception e) {
          System.out.println(e);
      }
}
public void loadVehi(){
    try{
ResultSet rs = DBMS.search("SELECT * FROM vehicle");
jComboBox7.removeAllItems();
          
          while (rs.next()) {              
              String name = rs.getString("number");
              jComboBox7.addItem(name);
          }
      } catch (Exception e) {
          System.out.println(e);
      }
}
public void loadTable(){
   if(jComboBox7.getItemCount()!=0){
    try {
          String v_id = jComboBox7.getSelectedItem().toString();
          ResultSet rs4 = DBMS.search("SELECT * FROM loading WHERE `vehicle_num`='"+v_id+"' ORDER BY CAST(`stock_id` AS unsigned) ASC");
          TableModel tm = jTable1.getModel(); 
          DefaultTableModel dtm = (DefaultTableModel) tm;
          dtm.setRowCount(0);
          
          jLabel24.setText("0.00");
          Double total = 0.00;
          
          while (rs4.next()) {
              String p_id = rs4.getString("stock_id");
              ResultSet rs = DBMS.search("SELECT * FROM stock WHERE `id`='"+p_id+"'");
              Vector<String> v = new Vector<>();
              v.add(rs4.getString("id"));
              v.add(p_id);
              
              if(rs.next()){
              ResultSet rs2 = DBMS.search("SELECT `name` FROM category WHERE `id`='"+rs.getString("cate_id")+"'");
              if(rs2.next()){
                  v.add(rs2.getString("name"));
              }
              v.add(rs.getString("name"));
              v.add(rs.getString("weight"));
              v.add(rs.getString("sell_p"));
              v.add(rs.getString("qty_i_b"));
              String qt = rs4.getString("qty");
              String q_i_b = rs.getString("qty_i_b");
              Double x1 = Double.valueOf(qt);
              Double y1 = Double.valueOf(q_i_b);
              Double xy = x1/y1;
              int xy1 = xy.intValue();
              v.add(String.valueOf(xy1));
              Double xy2 = Double.valueOf(xy1);
              Double xy3 = xy2*y1;
              Double xy4 = x1-xy3;
              int xy5 = xy4.intValue();
              v.add(String.valueOf(xy5));
              v.add(qt);
              String sp = rs.getString("sell_p");
          Double d_sp = Double.valueOf(sp);
           total += d_sp*x1;
              }
              v.add("0");
              v.add("0");
              dtm.addRow(v);
          }
          DecimalFormat df = new DecimalFormat("#.00");
          String t = df.format(total);
           jLabel24.setText(t);
      } catch (Exception e) {
          System.out.println(e);
      }
   }
}
}
