/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Database.DBMS;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Madushanka
 */
public class load_history extends javax.swing.JFrame {

    /**
     * Creates new form grn
     */
    public load_history() {
        initComponents();
        loadVehi();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    String l_id = "0";
    String qty = "0";
    DecimalFormat df = new DecimalFormat("#.00");
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(200, 200, 242));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Loading History", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 20), new java.awt.Color(0, 0, 204))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(200, 200, 242));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Vehicle Detailes", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 15), new java.awt.Color(0, 51, 153)))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel10.setText("Vehicle");

        jComboBox7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox7.setToolTipText("");
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setText("Date");

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jDateChooser1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(95, 95, 95)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(jComboBox7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Name", "Weight", "Bal Box", "Bal Unbox", "LD Box", "LD Unbox", "UNL Box", "UNL Unbox", "ExF Box ", "ExF Unbox", "ExT Box", "ExT Unbox"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
            jTable1.getColumnModel().getColumn(9).setResizable(false);
            jTable1.getColumnModel().getColumn(10).setResizable(false);
            jTable1.getColumnModel().getColumn(11).setResizable(false);
            jTable1.getColumnModel().getColumn(12).setResizable(false);
        }

        jButton3.setBackground(new java.awt.Color(0, 204, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("Search");
        jButton3.setContentAreaFilled(false);
        jButton3.setOpaque(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/refresh.png"))); // NOI18N
        jButton9.setContentAreaFilled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(267, 267, 267))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton9)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code her
        loadVehi();
        TableModel tm = jTable1.getModel(); 
          DefaultTableModel dtm = (DefaultTableModel) tm;
          dtm.setRowCount(0);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            if(jDateChooser1.getDate()!=null){
                TableModel tm = jTable1.getModel(); 
                DefaultTableModel dtm = (DefaultTableModel) tm;
                dtm.setRowCount(0);
                
             SimpleDateFormat sdf =new SimpleDateFormat("yyyy-MM-dd");
             String date = sdf.format(jDateChooser1.getDate());
            String v = jComboBox7.getSelectedItem().toString();
            String b = "Balance stock";
            String e = "Exchange";
            String l = "Loading";
            String u = "Unloading";
            ResultSet rs1 = DBMS.search("SELECT * FROM st_info WHERE `type`='"+b+"' AND `vehicle_f`='"+v+"' AND `date`='"+date+"' ");
            if(rs1.next()){
            String b_id = rs1.getString("id");
            ResultSet rs2 = DBMS.search("SELECT * FROM st_details WHERE `st_info_id`='"+b_id+"' ");
                while (rs2.next()) {
                    Vector<String> vv = new Vector<>();
                    vv.add(rs2.getString("stock_id"));
                    ResultSet rs3 = DBMS.search("SELECT * FROM stock WHERE `id`='"+rs2.getString("stock_id")+"'");
                    String q_i_b = "";
                    if(rs3.next()){
                    vv.add(rs3.getString("name"));
                    vv.add(rs3.getString("weight"));
                    q_i_b = rs3.getString("qty_i_b");
                    }
                    String qt = rs2.getString("qty");
                    Double x1 = Double.valueOf(qt);
                    Double y1 = Double.valueOf(q_i_b);
                    Double xy = x1/y1;
                    int xy1 = xy.intValue();
                    vv.add(String.valueOf(xy1));
                    Double xy2 = Double.valueOf(xy1);
                    Double xy3 = xy2*y1;
                    Double xy4 = x1-xy3;
                    int xy5 = xy4.intValue();
                    vv.add(String.valueOf(xy5));
                    vv.add("0");
                    vv.add("0");
                    vv.add("0");
                    vv.add("0");
                    vv.add("0");
                    vv.add("0");
                    vv.add("0");
                    vv.add("0");
                    dtm.addRow(vv);
                }
                ResultSet rs5 = DBMS.search("SELECT * FROM st_info WHERE `type`='"+l+"' AND `vehicle_f`='"+v+"' AND `date`='"+date+"' ");
                if(rs5.next()){
                    String l_id = rs5.getString("id");
                    //System.out.println(l_id);
                    ResultSet rs6 = DBMS.search("SELECT * FROM st_details WHERE `st_info_id`='"+l_id+"' ");
                    while (rs6.next()) {                        
                        String st_id = rs6.getString("stock_id");
                        //System.out.println(st_id);
                        ResultSet rs7 = DBMS.search("SELECT * FROM st_info WHERE `type`='"+b+"' AND `vehicle_f`='"+v+"' AND `date`='"+date+"' ");
                        if(rs7.next()){
                            String b_id1 = rs7.getString("id");
                            //System.out.println(b_id1);
                            ResultSet rs12 = DBMS.search("SELECT * FROM st_details WHERE `st_info_id`='"+b_id1+"' AND `stock_id`='"+st_id+"' ");
                            if(rs12.next()==false){
                            ResultSet rs9 = DBMS.search("SELECT * FROM st_details WHERE `st_info_id`='"+l_id+"' AND `stock_id`='"+st_id+"' ");
                            if(rs9.next()){
                                //System.out.println("rs9.next");
                            Vector<String> vvv = new Vector<>();
                            vvv.add(rs9.getString("stock_id"));
                            ResultSet rs10 = DBMS.search("SELECT * FROM stock WHERE `id`='"+rs9.getString("stock_id")+"'");
                    String q_i_b = "";
                    if(rs10.next()){
                    vvv.add(rs10.getString("name"));
                    vvv.add(rs10.getString("weight"));
                    vvv.add("0");
                    vvv.add("0");
                    q_i_b = rs10.getString("qty_i_b");
                    }
                    String qt = rs9.getString("qty");
                    Double x1 = Double.valueOf(qt);
                    Double y1 = Double.valueOf(q_i_b);
                    Double xy = x1/y1;
                    int xy1 = xy.intValue();
                    vvv.add(String.valueOf(xy1));
                    Double xy2 = Double.valueOf(xy1);
                    Double xy3 = xy2*y1;
                    Double xy4 = x1-xy3;
                    int xy5 = xy4.intValue();
                    vvv.add(String.valueOf(xy5));
                    vvv.add("0");
                    vvv.add("0");
                    vvv.add("0");
                    vvv.add("0");
                    vvv.add("0");
                    vvv.add("0");
                    dtm.addRow(vvv);
                               //System.out.println("Add raw");
                            }
                            }
                        }
                    }
                }
            }
            int rc = jTable1.getRowCount();
            for(int x = 0;x<rc;x++){
            String p_id = jTable1.getValueAt(x, 0).toString();
            ResultSet rs20 = DBMS.search("SELECT * FROM stock WHERE `id`='"+p_id+"'");
            String q_i_b = "0";
            if(rs20.next()){
            q_i_b = rs20.getString("qty_i_b");
            //Double d_q_i_b = Double.valueOf(q_i_b);
            }
            Double d_q_i_b = Double.valueOf(q_i_b);
            
            ResultSet rs24 = DBMS.search("SELECT * FROM st_info WHERE `type`='"+l+"' AND `vehicle_f`='"+v+"' AND `date`='"+date+"' ");
             if(rs24.next()){
             String l_id = rs24.getString("id");
             ResultSet rs22 = DBMS.search("SELECT * FROM st_details WHERE `st_info_id`='"+l_id+"' AND `stock_id`='"+p_id+"'");
             Double qt = 0.0;
             while(rs22.next()){
               qt += Double.valueOf(rs22.getString("qty"));
             }
                    Double x1 = qt;
                    Double y1 = d_q_i_b;
                    Double xy = x1/y1;
                    int xy1 = xy.intValue();
                    tm.setValueAt(String.valueOf(xy1), x, 5);
                    Double xy2 = Double.valueOf(xy1);
                    Double xy3 = xy2*y1;
                    Double xy4 = x1-xy3;
                    int xy5 = xy4.intValue();
                    tm.setValueAt(String.valueOf(xy5), x, 6);
             }
            
             ResultSet rs21 = DBMS.search("SELECT * FROM st_info WHERE `type`='"+u+"' AND `vehicle_f`='"+v+"' AND `date`='"+date+"' ");
             if(rs21.next()){
             String u_id = rs21.getString("id");
             ResultSet rs22 = DBMS.search("SELECT * FROM st_details WHERE `st_info_id`='"+u_id+"' AND `stock_id`='"+p_id+"'");
             Double qt = 0.0;
             while(rs22.next()){
               qt += Double.valueOf(rs22.getString("qty"));
             }
                    Double x1 = qt;
                    Double y1 = d_q_i_b;
                    Double xy = x1/y1;
                    int xy1 = xy.intValue();
                    tm.setValueAt(String.valueOf(xy1), x, 7);
                    Double xy2 = Double.valueOf(xy1);
                    Double xy3 = xy2*y1;
                    Double xy4 = x1-xy3;
                    int xy5 = xy4.intValue();
                    tm.setValueAt(String.valueOf(xy5), x, 8);
             }
             
             ResultSet rs25 = DBMS.search("SELECT * FROM st_info WHERE `type`='"+e+"' AND `vehicle_f`='"+v+"' AND `date`='"+date+"' ");
             if(rs25.next()){
             String e_id = rs25.getString("id");
             ResultSet rs22 = DBMS.search("SELECT * FROM st_details WHERE `st_info_id`='"+e_id+"' AND `stock_id`='"+p_id+"'");
             Double qt = 0.0;
             while(rs22.next()){
               qt += Double.valueOf(rs22.getString("qty"));
             }
                    Double x1 = qt;
                    Double y1 = d_q_i_b;
                    Double xy = x1/y1;
                    int xy1 = xy.intValue();
                    tm.setValueAt(String.valueOf(xy1), x, 9);
                    Double xy2 = Double.valueOf(xy1);
                    Double xy3 = xy2*y1;
                    Double xy4 = x1-xy3;
                    int xy5 = xy4.intValue();
                    tm.setValueAt(String.valueOf(xy5), x, 10);
             }
             
             ResultSet rs27 = DBMS.search("SELECT * FROM st_info WHERE `type`='"+e+"' AND `vehicle_t`='"+v+"' AND `date`='"+date+"' ");
             if(rs27.next()){
             String e_id = rs27.getString("id");
             ResultSet rs22 = DBMS.search("SELECT * FROM st_details WHERE `st_info_id`='"+e_id+"' AND `stock_id`='"+p_id+"'");
             Double qt = 0.0;
             while(rs22.next()){
               qt += Double.valueOf(rs22.getString("qty"));
             }
                    Double x1 = qt;
                    Double y1 = d_q_i_b;
                    Double xy = x1/y1;
                    int xy1 = xy.intValue();
                    tm.setValueAt(String.valueOf(xy1), x, 11);
                    Double xy2 = Double.valueOf(xy1);
                    Double xy3 = xy2*y1;
                    Double xy4 = x1-xy3;
                    int xy5 = xy4.intValue();
                    tm.setValueAt(String.valueOf(xy5), x, 12);
             }
             
            }
            }else{
             JOptionPane.showMessageDialog(this, "Please Select Date", "Search History", JOptionPane.INFORMATION_MESSAGE);
             }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(load_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(load_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(load_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(load_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new load_history().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox7;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

public void loadVehi(){
    try{
ResultSet rs = DBMS.search("SELECT * FROM vehicle");
jComboBox7.removeAllItems();
          
          while (rs.next()) {              
              String name = rs.getString("number");
              jComboBox7.addItem(name);
          }
      } catch (Exception e) {
          System.out.println(e);
      }
}

}
