/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Database.DBMS;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import static sun.net.www.MimeTable.loadTable;

/**
 *
 * @author Madushanka
 */
public class sale_details extends javax.swing.JFrame {

    /**
     * Creates new form grn
     */
    public sale_details() {
        initComponents();
        loadVehi();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton7 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(200, 200, 242));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Sale Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 20), new java.awt.Color(0, 0, 204))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(200, 200, 242));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Search Sale Details", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 15), new java.awt.Color(0, 51, 153)))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel11.setText("Date");

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jDateChooser1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jDateChooser2.setDateFormatString("yyyy-MM-dd");
        jDateChooser2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/search.png"))); // NOI18N
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jCheckBox1.setBackground(new java.awt.Color(200, 200, 242));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox1.setText("Date Range");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setToolTipText("");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel12.setText("Vehicle");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel11)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jCheckBox1)))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Table ID", "Amount", "Payment", "Balance", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/refresh.png"))); // NOI18N
        jButton9.setContentAreaFilled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel18.setText("Amount  :");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel19.setText("0.00");

        jButton4.setBackground(new java.awt.Color(204, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("One Sale Details");
        jButton4.setContentAreaFilled(false);
        jButton4.setOpaque(true);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel20.setText("Payment :");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel21.setText("0.00");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel22.setText("0.00");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel23.setText("Balance :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton9))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        DecimalFormat df = new DecimalFormat("#.00");
        try{
        SimpleDateFormat sdf =new SimpleDateFormat("yyyy-MM-dd");
        String date1 = sdf.format(jDateChooser2.getDate());
        TableModel tm = jTable1.getModel();
        DefaultTableModel dtm = (DefaultTableModel) tm;
        dtm.setRowCount(0);
        jLabel19.setText("0.00");
        jLabel21.setText("0.00");
        jLabel22.setText("0.00");
        Double l_a = 0.00;
        Double l_p = 0.00;
        Double l_b = 0.00;
        boolean b = jCheckBox1.isSelected();
        String s_i = jComboBox1.getSelectedItem().toString();
        if(b==false){  
          if(s_i.equals("All")){
          ResultSet rs = DBMS.search("SELECT * FROM sale WHERE `date`='"+date1+"'");
              while (rs.next()) {                  
                  String t_id = rs.getString("id");
                  String date = rs.getString("date");
                  String amount = rs.getString("amount");
                  String payment = rs.getString("payment");
                  String balance = rs.getString("balance");
                  Double amu = Double.valueOf(amount);
                  l_a+=amu;
                  Double pay = Double.valueOf(payment);
                  l_p+=pay;
                  Double bal = Double.valueOf(balance);
                  l_b+=bal;
                  Vector<String> v = new Vector<>();
                  v.add(t_id);
                  v.add(df.format(Double.valueOf(amount)));
                  v.add(df.format(Double.valueOf(payment)));
                  v.add(df.format(Double.valueOf(balance)));
                  v.add(date);
                  dtm.addRow(v);
              }
              jLabel19.setText(String.valueOf(df.format(l_a)));
              jLabel21.setText(String.valueOf(df.format(l_p)));
              jLabel22.setText(String.valueOf(df.format(l_b)));
          }else{
          ResultSet rs = DBMS.search("SELECT * FROM sale WHERE `date`='"+date1+"' AND `name`='"+s_i+"'");
              while (rs.next()) {                  
                  String t_id = rs.getString("id");
                  String date = rs.getString("date");
                  String amount = rs.getString("amount");
                  String payment = rs.getString("payment");
                  String balance = rs.getString("balance");
                  Double amu = Double.valueOf(amount);
                  l_a+=amu;
                  Double pay = Double.valueOf(payment);
                  l_p+=pay;
                  Double bal = Double.valueOf(balance);
                  l_b+=bal;
                  Vector<String> v = new Vector<>();
                  v.add(t_id);
                  v.add(df.format(Double.valueOf(amount)));
                  v.add(df.format(Double.valueOf(payment)));
                  v.add(df.format(Double.valueOf(balance)));
                  v.add(date);
                  dtm.addRow(v);
              }
              jLabel19.setText(String.valueOf(df.format(l_a)));
              jLabel21.setText(String.valueOf(df.format(l_p)));
              jLabel22.setText(String.valueOf(df.format(l_b)));
          }
        }else{
            if(s_i.equals("All")){
             String date2 = sdf.format(jDateChooser1.getDate());
          ResultSet rs = DBMS.search("SELECT * FROM sale WHERE `date` BETWEEN '"+date1+"' AND '"+date2+"'");
              while (rs.next()) {                  
                  String t_id = rs.getString("id");
                  String date = rs.getString("date");
                  String amount = rs.getString("amount");
                  String payment = rs.getString("payment");
                  String balance = rs.getString("balance");
                  Double amu = Double.valueOf(amount);
                  l_a+=amu;
                  Double pay = Double.valueOf(payment);
                  l_p+=pay;
                  Double bal = Double.valueOf(balance);
                  l_b+=bal;
                  Vector<String> v = new Vector<>();
                  v.add(t_id);
                  v.add(df.format(Double.valueOf(amount)));
                  v.add(df.format(Double.valueOf(payment)));
                  v.add(df.format(Double.valueOf(balance)));
                  v.add(date);
                  dtm.addRow(v);
              }
              jLabel19.setText(String.valueOf(df.format(l_a)));
              jLabel21.setText(String.valueOf(df.format(l_p)));
              jLabel22.setText(String.valueOf(df.format(l_b)));
            }else{
             String date2 = sdf.format(jDateChooser1.getDate());
          ResultSet rs = DBMS.search("SELECT * FROM sale WHERE `name`='"+s_i+"' AND `date` BETWEEN '"+date1+"' AND '"+date2+"'");
              while (rs.next()) {                  
                  String t_id = rs.getString("id");
                  String date = rs.getString("date");
                  String amount = rs.getString("amount");
                  String payment = rs.getString("payment");
                  String balance = rs.getString("balance");
                  Double amu = Double.valueOf(amount);
                  l_a+=amu;
                  Double pay = Double.valueOf(payment);
                  l_p+=pay;
                  Double bal = Double.valueOf(balance);
                  l_b+=bal;
                  Vector<String> v = new Vector<>();
                  v.add(t_id);
                  v.add(df.format(Double.valueOf(amount)));
                  v.add(df.format(Double.valueOf(payment)));
                  v.add(df.format(Double.valueOf(balance)));
                  v.add(date);
                  dtm.addRow(v);
              }
              jLabel19.setText(String.valueOf(df.format(l_a)));
              jLabel21.setText(String.valueOf(df.format(l_p)));
              jLabel22.setText(String.valueOf(df.format(l_b)));
            }
        }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code he
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if(row!=-1){
            String t_id = jTable1.getValueAt(row,0).toString();
            one_sale_details one = new one_sale_details(t_id);
            one.setVisible(true);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        DecimalFormat df = new DecimalFormat("#.00");
        try {
            if(jComboBox1.getItemCount()!=0){
                String s_i = jComboBox1.getSelectedItem().toString();
                if(s_i.equals("All")){
                    Double a_t = 0.0;
                    Double p_t = 0.0;
                    Double b_t = 0.0;
                ResultSet rs = DBMS.search("SELECT * FROM sale");
                TableModel tm = jTable1.getModel(); 
                 DefaultTableModel dtm = (DefaultTableModel) tm;
                dtm.setRowCount(0);
                while(rs.next()){
                    Vector<String> v = new Vector<>();
                    v.add(rs.getString("id"));
                    String amount = rs.getString("amount");
                    v.add(df.format(Double.valueOf(amount)));
                    Double a_t1 = Double.valueOf(amount);
                    a_t+=a_t1;
                    String payment = rs.getString("payment");
                    v.add(df.format(Double.valueOf(payment)));
                   Double p_t1 = Double.valueOf(payment);
                   p_t+=p_t1;
                    String balance = rs.getString("balance");
                    v.add(df.format(Double.valueOf(balance)));
                   Double b_t1 = Double.valueOf(balance);
                   b_t+=b_t1;
                    v.add(rs.getString("date"));
                    dtm.addRow(v);
                }
                jLabel21.setText(df.format(p_t));
                jLabel22.setText(df.format(b_t));
                jLabel19.setText(df.format(a_t));
                }else{
               ResultSet rs = DBMS.search("SELECT * FROM sale WHERE `name`='"+s_i+"'");
               Double a_t = 0.0;
                    Double p_t = 0.0;
                    Double b_t = 0.0;
                TableModel tm = jTable1.getModel(); 
                 DefaultTableModel dtm = (DefaultTableModel) tm;
                dtm.setRowCount(0);
                    while (rs.next()) {                        
                         Vector<String> v = new Vector<>();
                    v.add(rs.getString("id"));
                    String amount = rs.getString("amount");
                    v.add(df.format(Double.valueOf(amount)));
                    a_t += Double.valueOf(amount);
                    String payment = rs.getString("payment");
                    v.add(df.format(Double.valueOf(payment)));
                    p_t += Double.valueOf(payment);
                    String balance = rs.getString("balance");
                    v.add(df.format(Double.valueOf(balance)));
                    b_t += Double.valueOf(balance);
                    v.add(rs.getString("date"));
                    dtm.addRow(v);
                    }
                 jLabel19.setText(String.valueOf(df.format(a_t)));
                jLabel21.setText(String.valueOf(df.format(p_t)));
                jLabel22.setText(String.valueOf(df.format(b_t)));
                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sale_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sale_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sale_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sale_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sale_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
public void loadVehi(){
    try{
ResultSet rs = DBMS.search("SELECT * FROM vehicle");
jComboBox1.removeAllItems();
          jComboBox1.addItem("All");
          while (rs.next()) {              
              String name = rs.getString("number");
              jComboBox1.addItem(name);
          }
      } catch (Exception e) {
          System.out.println(e);
      }
}
}
