/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Database.DBMS;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Madushanka
 */
public class unloading_sale extends javax.swing.JFrame {

    /**
     * Creates new form grn
     */
    public unloading_sale() {
        initComponents();
        loadCate();
        loadVehi();
        jTextField9.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jComboBox9 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(200, 200, 242));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Unloading With Sale", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 20), new java.awt.Color(0, 0, 204))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(200, 200, 242));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Add product details", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 15), new java.awt.Color(0, 51, 153)))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("Vehicle");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setText("Category");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setToolTipText("");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setText("<html>Name &<br/>Weight</html>");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setText("Selling price");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel12.setText("Unit in Box");

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox2.setToolTipText("");

        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox3.setToolTipText("");

        jComboBox6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox6.setToolTipText("");
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel10.setText("Product ID");

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField9KeyReleased(evt);
            }
        });

        jComboBox9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox9.setToolTipText("");
        jComboBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox9ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setText("Date");

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jDateChooser1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addGap(35, 35, 35))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(55, 55, 55)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(20, 20, 20)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField9)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Category", "Name", "Weight", "<html>Loading<br/>Box</html>", "<html>Loading<br/>Unbox Qty</html>", "<html>Balance<br/>Box</html>", "<html>Balance<br/>Unbox Qty</html>", "<html>Sale<br/>Box</html>", "<html>Sale<br/>Unbox Qty</html>", "<html>Sale<br/>Qty</html>", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(8).setResizable(false);
            jTable1.getColumnModel().getColumn(9).setResizable(false);
            jTable1.getColumnModel().getColumn(10).setResizable(false);
            jTable1.getColumnModel().getColumn(11).setResizable(false);
        }

        jButton2.setBackground(new java.awt.Color(255, 102, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Add Product");
        jButton2.setContentAreaFilled(false);
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/refresh.png"))); // NOI18N
        jButton9.setContentAreaFilled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(200, 200, 242));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Payment", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("0.00");

        jButton1.setBackground(new java.awt.Color(102, 0, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Complete");
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setText("Total         :");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addGap(286, 286, 286)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel24)
                    .addComponent(jLabel30))
                .addGap(2, 2, 2))
        );

        jButton4.setBackground(new java.awt.Color(153, 255, 102));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Sale History");
        jButton4.setContentAreaFilled(false);
        jButton4.setOpaque(true);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 102, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Sale Calculate");
        jButton3.setContentAreaFilled(false);
        jButton3.setOpaque(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(496, 496, 496)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code her
        loadCate();
        loadVehi();
        jTextField9.grabFocus();
        jLabel24.setText("0.00");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         // TODO add your handling code here:
        try {
            String am = jLabel24.getText();
            String v = jComboBox9.getSelectedItem().toString();
            String aaa = "0";
            if(jDateChooser1.getDate()!=null && !am.equals("0.00")){
                SimpleDateFormat sdf =new SimpleDateFormat("yyyy-MM-dd");
                String date = sdf.format(jDateChooser1.getDate());
                DBMS.iud("INSERT INTO sale(`name`,`date`,`amount`,`payment`,`balance`) VALUES ('"+v+"','"+date+"','"+am+"','"+aaa+"','"+aaa+"')");
               
                int rc = jTable1.getRowCount();
                for(int x = 0;x<rc;x++){
                String p_id = jTable1.getValueAt(x, 0).toString();
                String s_q = jTable1.getValueAt(x, 10).toString();
                String amou = jTable1.getValueAt(x, 11).toString();
                if(!s_q.equals("0")){
                    //System.out.println("Sale "+p_id);
                    ResultSet rs1 = DBMS.search("SELECT MAX(`id`) FROM sale");
                if(rs1.next()){
                    String sale_id = rs1.getString(1);
                    DBMS.iud("INSERT INTO sale_details(`sale_id`,`stock_id`,`qty`,`amount`,`discount`) VALUES('"+sale_id+"','"+p_id+"','"+s_q+"','"+amou+"','"+aaa+"')");
                }
                }
                }
                DBMS.iud("DELETE FROM loading WHERE `vehicle_num`='"+v+"'");
                int rc1 = jTable1.getRowCount();
                for(int y = 0;y<rc1;y++){
                String p_id2 = jTable1.getValueAt(y, 0).toString();
                String b_bq2 = jTable1.getValueAt(y, 6).toString();
                String b_ubq2 = jTable1.getValueAt(y, 7).toString();
                if(!b_bq2.equals("0")|!b_ubq2.equals("0")){
                    //System.out.println("Loading "+p_id);
                    ResultSet rs = DBMS.search("SELECT * FROM stock WHERE `id`='"+p_id2+"'");
                    if(rs.next()){
                        String b_i_q2 = rs.getString("qty_i_b");
                        Double d_biq2 = Double.valueOf(b_i_q2);
                        Double d_b_bq2 = Double.valueOf(b_bq2);
                        Double d_b_ubq2 = Double.valueOf(b_ubq2);
                        Double d_a_bq2 = d_biq2*d_b_bq2;
                                d_a_bq2+=d_b_ubq2;
                        int a_b2 = d_a_bq2.intValue();
                        String s_ab2 = String.valueOf(a_b2);
                        DBMS.iud("INSERT INTO loading(`stock_id`,`vehicle_num`,`qty` ) VALUE('"+p_id2+"','"+v+"','"+s_ab2+"')");
                    }
                }
                }
                JOptionPane.showMessageDialog(this, "Unloading Success", "Unloading Sale", JOptionPane.INFORMATION_MESSAGE);
                jLabel24.setText("0.00");
            }else{
            JOptionPane.showMessageDialog(this, "Please select Date & Calculate First", "Unloading Sale", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        TableModel tm = jTable1.getModel();
        DefaultTableModel dtm = (DefaultTableModel)tm;
        try {
              String p_id = jTextField9.getText();
       String v = jComboBox9.getSelectedItem().toString();
       String q = "0";
       if(!p_id.isEmpty()){
           ResultSet rs = DBMS.search("SELECT * FROM loading WHERE `vehicle_num`='"+v+"' AND `stock_id`='"+p_id+"' ");
          if(rs.next()==false){
           DBMS.iud("INSERT INTO loading(`stock_id`,`vehicle_num`,`qty` ) VALUE('"+p_id+"','"+v+"','"+q+"')");
            ResultSet rs1 = DBMS.search("SELECT * FROM loading WHERE `vehicle_num`='"+v+"' AND `stock_id`='"+p_id+"' ");
            if(rs1.next()){
            Vector<String> v1 = new Vector<>();
            v1.add(rs1.getString("stock_id"));
             ResultSet rs2 = DBMS.search("SELECT * FROM stock WHERE `id`='"+rs1.getString("stock_id")+"'");
             if(rs2.next()){
             ResultSet rs3 = DBMS.search("SELECT `name` FROM category WHERE `id`='"+rs2.getString("cate_id")+"'");
              if(rs3.next()){
                  v1.add(rs3.getString("name"));
              }
              v1.add(rs2.getString("name"));
              v1.add(rs2.getString("weight"));
              v1.add("0");
              v1.add("0");
              v1.add("0");
              v1.add("0");
              v1.add("0");
              v1.add("0");
              v1.add("0");
              v1.add("0");
              
             }
             dtm.addRow(v1);
            }
            JOptionPane.showMessageDialog(this, "Success", "Add Loading Product", JOptionPane.INFORMATION_MESSAGE);
          }else{
          JOptionPane.showMessageDialog(this, "This Product Allready Add", "Add Loading Product", JOptionPane.INFORMATION_MESSAGE);
          }
          
       }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyReleased
        // TODO add your handling code here:
       /* String id = jTextField9.getText();
       if(!id.isEmpty()){
        try {
            ResultSet rs = DBMS.search("SELECT * FROM stock WHERE `id`='"+id+"'");
            if(rs.next()==true){
                String cate = rs.getString("cate_id");
                ResultSet rs1 = DBMS.search("SELECT * FROM category WHERE `id`='"+cate+"'");
                if(rs1.next()){
                String cate_n = rs1.getString("name");
                jComboBox1.setSelectedItem(cate_n);
                }
                String name = rs.getString("name");
                jComboBox6.addItem(name);
                jComboBox6.setSelectedItem(name);
                String sp = rs.getString("sell_p");
                jComboBox3.addItem(sp);
                jComboBox3.setSelectedItem(sp);
                String wei = rs.getString("weight");
                jComboBox4.addItem(wei);
                jComboBox4.setSelectedItem(wei);
                String ub = rs.getString("qty_i_b");
                jComboBox2.addItem(ub);
                jComboBox2.setSelectedItem(ub);
                jLabel16.setText(ub);
            }else{
                jComboBox2.removeAllItems();
                jComboBox3.removeAllItems();
                jComboBox4.removeAllItems();
                jComboBox6.removeAllItems();
                jLabel16.setText("0");
                jTextField7.setText("0");
                jTextField6.setText("0");
                jTextField8.setText("0");
                loadCate();
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
       }else{
       jComboBox2.removeAllItems();
                jComboBox3.removeAllItems();
                jComboBox4.removeAllItems();
                jComboBox6.removeAllItems();
                jLabel16.setText("0");
                jTextField7.setText("0");
                jTextField6.setText("0");
                jTextField8.setText("0");
                loadCate();
       }*/
    }//GEN-LAST:event_jTextField9KeyReleased

    private void jComboBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox9ActionPerformed
        // TODO add your handling code here:
         TableModel tm = jTable1.getModel();
        DefaultTableModel dtm = (DefaultTableModel)tm;
        dtm.setRowCount(0);
        try {
       
       if(jComboBox9.getItemCount()!=0){
           String v = jComboBox9.getSelectedItem().toString();
            ResultSet rs1 = DBMS.search("SELECT * FROM loading WHERE `vehicle_num`='"+v+"' ORDER BY CAST(`stock_id` AS unsigned) ASC");
            while(rs1.next()){
            Vector<String> v1 = new Vector<>();
            v1.add(rs1.getString("stock_id"));
             ResultSet rs2 = DBMS.search("SELECT * FROM stock WHERE `id`='"+rs1.getString("stock_id")+"'");
             if(rs2.next()){
             ResultSet rs3 = DBMS.search("SELECT `name` FROM category WHERE `id`='"+rs2.getString("cate_id")+"'");
              if(rs3.next()){
                  v1.add(rs3.getString("name"));
              }
              v1.add(rs2.getString("name"));
              v1.add(rs2.getString("weight"));
              String qt = rs1.getString("qty");
              String q_i_b = "";
              ResultSet rs4 = DBMS.search("SELECT `qty_i_b` FROM stock WHERE `id`='"+rs1.getString("stock_id")+"'");
              if(rs4.next()){
              q_i_b = rs4.getString("qty_i_b");
              }
              Double x1 = Double.valueOf(qt);
              Double y1 = Double.valueOf(q_i_b);
              Double xy = x1/y1;
              int xy1 = xy.intValue();
              v1.add(String.valueOf(xy1));
              Double xy2 = Double.valueOf(xy1);
              Double xy3 = xy2*y1;
              Double xy4 = x1-xy3;
              int xy5 = xy4.intValue();
              v1.add(String.valueOf(xy5));
              v1.add("0");
              v1.add("0");
              v1.add("0");
              v1.add("0");
              v1.add("0");
              v1.add("0");
              
             }
             dtm.addRow(v1);
            }
          
       }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jComboBox9ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        sale_details s = new sale_details();
        s.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
      // TODO add your handling code here:
       if(jComboBox6.getItemCount()!=0){
            String c_n = jComboBox1.getSelectedItem().toString();
           try {
               if(c_n.equals("All")){
                String txt = jComboBox6.getSelectedItem().toString();
               String name = txt.replaceAll("\\d", "");
               name = name.replaceAll(".$", "");
               name = name.trim();
               String n = name;
               String weight = txt.replaceAll("[^\\d.]", "");
               String g = "g";
               String wg = weight+g;
                 ResultSet rs2 = DBMS.search("SELECT * FROM stock WHERE `name`='"+n+"' AND `weight`='"+wg+"'");
                 if(rs2.next()){
                 String id = rs2.getString("id");
                 String sp = rs2.getString("sell_p");
                 String ub = rs2.getString("qty_i_b");
                 String c = rs2.getString("cate_id");
                 ResultSet rs3 = DBMS.search("SELECT * FROM category WHERE `id`='"+c+"'");
                 if(rs3.next()){
                 //jComboBox1.setSelectedItem(rs3.getString("name"));
                 jLabel9.setText(rs3.getString("name"));
                 }
                 jComboBox3.removeAllItems();
                 jComboBox2.removeAllItems();
                 jComboBox3.addItem(sp);
                 jComboBox2.addItem(ub);
                 jTextField9.setText(id);
                 }
               }else{
               String txt = jComboBox6.getSelectedItem().toString();             
               String name = txt.replaceAll("\\d", "");
               name = name.replaceAll(".$", "");
               name = name.trim();
               String n = name;
               String weight = txt.replaceAll("[^\\d.]", "");
               String g = "g";
               String wg = weight+g;
                ResultSet rs = DBMS.search("SELECT * FROM category WHERE `name`='"+c_n+"'");
                if(rs.next()){
                 String c_id = rs.getString("id");
                 /*System.out.println(name);
                 System.out.println(wg);
                 System.out.println(c_id);*/
                 ResultSet rs2 = DBMS.search("SELECT * FROM stock WHERE `cate_id`='"+c_id+"' AND `name`='"+n+"' AND `weight`='"+wg+"'");
                 if(rs2.next()){
                 String id = rs2.getString("id");
                 String sp = rs2.getString("sell_p");
                 String ub = rs2.getString("qty_i_b");
                 jComboBox3.removeAllItems();
                 jComboBox2.removeAllItems();
                 jComboBox3.addItem(sp);
                 jComboBox2.addItem(ub);
                 jTextField9.setText(id);
                 }
                }
               }
           } catch (Exception e) {
               System.out.println(e);
           }
       }else{
       jTextField9.setText("");
       jComboBox3.removeAllItems();
       jComboBox2.removeAllItems();
       }
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        try {
       if(jComboBox1.getItemCount()!=0){
       String c_n = jComboBox1.getSelectedItem().toString();
       jComboBox6.removeAllItems();
           
                if(c_n.equals("All")){
                ResultSet rs1 = DBMS.search("SELECT * FROM stock");
                    while (rs1.next()) {                        
                        String name = rs1.getString("name");
                        String weight = rs1.getString("weight");
                        String sp = " ";
                        String n_s_w = name+sp+weight;
                        jComboBox6.addItem(n_s_w);
                    }
                }else{
                    jLabel9.setText(" ");
                ResultSet rs = DBMS.search("SELECT * FROM category WHERE `name`='"+c_n+"'");
                if(rs.next()){
                 String c_id = rs.getString("id");
                 ResultSet rs1 = DBMS.search("SELECT * FROM stock WHERE `cate_id`='"+c_id+"'");
                    while (rs1.next()) {                        
                        String name = rs1.getString("name");
                        String weight = rs1.getString("weight");
                        String sp = " ";
                        String n_s_w = name+sp+weight;
                        jComboBox6.addItem(n_s_w);
                    }
                }
                }
           }
           } catch (Exception e) {
               System.out.println(e);
           }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        TableModel tm = jTable1.getModel();
        DefaultTableModel dtm = (DefaultTableModel)tm;
        DecimalFormat df = new DecimalFormat("#.00");
        try {
            int rc = jTable1.getRowCount();
            Double am = 0.00;
            for(int x = 0;x<rc;x++){
            String p_id = jTable1.getValueAt(x, 0).toString();
            String b_bq = jTable1.getValueAt(x, 6).toString();
            String b_ubq = jTable1.getValueAt(x, 7).toString();
            String l_bq = jTable1.getValueAt(x, 4).toString();
            String l_ubq = jTable1.getValueAt(x, 5).toString();
            if(!b_bq.equals("0")|!b_ubq.equals("0")){
            ResultSet rs = DBMS.search("SELECT * FROM stock WHERE `id`='"+p_id+"'");
            if(!l_bq.equals("0")|!l_ubq.equals("0")){
            if(rs.next()){
            String b_i_q = rs.getString("qty_i_b");
            Double d_biq = Double.valueOf(b_i_q);
            Double d_b_bq = Double.valueOf(b_bq);
            Double d_b_ubq = Double.valueOf(b_ubq);
            Double d_l_bq = Double.valueOf(l_bq);
            Double d_l_ubq = Double.valueOf(l_ubq);
            Double d_a_bq = (d_biq*d_b_bq)+d_b_ubq;
            Double d_a_lq = (d_biq*d_l_bq)+d_l_ubq;
            Double d_s_q = d_a_lq-d_a_bq;
            String sp = rs.getString("sell_p");
            Double d_sp = Double.valueOf(sp);
            Double d_sa = d_s_q*d_sp;
            tm.setValueAt(df.format(d_sa), x, 11);
            Double xy = d_s_q/d_biq;
              int xy1 = xy.intValue();
              //v.add(String.valueOf(xy1));
              tm.setValueAt(xy1, x, 8);
              Double xy2 = Double.valueOf(xy1);
              Double xy3 = xy2*d_biq;
              Double xy4 = d_s_q-xy3;
              int xy5 = xy4.intValue();
              //v.add(String.valueOf(xy5));
              tm.setValueAt(xy5, x, 9);
              //v.add(String.valueOf(d_s_q));
              int aa = d_s_q.intValue();
              tm.setValueAt(aa, x, 10);
              am+=d_sa;
            }
            }
            }else{
            //all sale
            ResultSet rs1 = DBMS.search("SELECT * FROM stock WHERE `id`='"+p_id+"'");
            if(rs1.next()){
            String b_i_q = rs1.getString("qty_i_b");
            Double d_biq = Double.valueOf(b_i_q);
            Double d_l_bq = Double.valueOf(l_bq);
            Double d_l_ubq = Double.valueOf(l_ubq);
            Double d_s_q = (d_biq*d_l_bq)+d_l_ubq;
            String sp = rs1.getString("sell_p");
            Double d_sp = Double.valueOf(sp);
            Double d_sa = d_s_q*d_sp;
            tm.setValueAt(df.format(d_sa), x, 11);
            am+=d_sa;
             Double xy = d_s_q/d_biq;
              int xy1 = xy.intValue();
              //v.add(String.valueOf(xy1));
              tm.setValueAt(xy1, x, 8);
              Double xy2 = Double.valueOf(xy1);
              Double xy3 = xy2*d_biq;
              Double xy4 = d_s_q-xy3;
              int xy5 = xy4.intValue();
              //v.add(String.valueOf(xy5));
              tm.setValueAt(xy5, x, 9);
              //v.add(String.valueOf(d_s_q));
              int aa = d_s_q.intValue();
              tm.setValueAt(aa, x, 10);
              
            }
            }
            jLabel24.setText(df.format(am));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(unloading_sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(unloading_sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(unloading_sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(unloading_sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new unloading_sale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

public void loadCate(){
    try{
ResultSet rs = DBMS.search("SELECT * FROM category");
jComboBox1.removeAllItems();
           jComboBox1.addItem("All");
          while (rs.next()) {              
              String name = rs.getString("name");
              jComboBox1.addItem(name);
          }
      } catch (Exception e) {
          System.out.println(e);
      }
}
public void loadVehi(){
    try{
ResultSet rs = DBMS.search("SELECT * FROM vehicle");
jComboBox9.removeAllItems();
          
          while (rs.next()) {              
              String name = rs.getString("number");
              jComboBox9.addItem(name);
          }
      } catch (Exception e) {
          System.out.println(e);
      }
}
}
